name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  version_or_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - run: npm i -g pnpm@9
      - run: pnpm install --frozen-lockfile=false
      - uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm -r --filter ./packages/* publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
